### PR TITLE
first batch of python stuff

### PR DESCRIPTION
**Pull request by sknsean**
- still missing the systemd service files
- this a dump from what we had in our internal meta-layer so I will need to build test it

Comments welcome :+1:

### CODE REVIEW

**Review by jluebbe — APPROVED** [review]
Looks good to me for now.
For the service files, I'd suggest splitting out the coordinator URL to an env file to be loaded by the service unit (so it's easy to override that in a custom layer).

**Comment by sknsean** [comment]
systemd service added

**Comment by henriknj** [comment]
Looks good, but I guess you forgot to remove some dependencies not required by labgrid.
Such as traferet/traferet-config etc. ?

**Comment by jluebbe** [comment]
> Looks good, but I guess you forgot to remove some dependencies not required by labgrid.
> Such as traferet/traferet-config etc. ?

trafaret is used by PR #3 (labgrid-powerrelay).

**Review by jluebbe — APPROVED** [review]

**Pull request merged**
