### PR TITLE
scarthgap: update labgrid master version and add support for gRPC

### PR DESCRIPTION
**Pull request by hnez**
This is a backport of #58 to the scarthgap branch.

### CODE REVIEW

**Comment by Emantor** [comment]
We should also fix the commit prefixes to `meta-labgrid`, also upstream commit information would be nice to be included in the commits, `git cherry-pick -x` provides this.

**Review by Emantor — CHANGES_REQUESTED** [review]
We should also fix the commit prefixes to `meta-labgrid`, also a master commit reference would be nice to be included in the commits, `git cherry-pick -x` provides this.

**Comment by hnez** [comment]
> We should also fix the commit prefixes to `meta-labgrid`,

Oh. Did not notice that. We do not have `meta…` prefixes in other commits in this repo, so I have removed them.

> also a master commit reference would be nice to be included in the commits, `git cherry-pick -x` provides this.

Cool. Did not know that. I've re-picked the two commits.

**Review by Emantor — APPROVED** [review]

**Comment by Emantor** [comment]
Thanks!

**Pull request merged**
