### PR TITLE
python3-labgrid: use a SRCBRANCH variable in the git URL

### PR DESCRIPTION
**Pull request by jluebbe**
This makes it easier to switch the branch together with the SRCREV using .bbappend or .conf files.

### CODE REVIEW

**Review by ejoerns — COMMENTED** [review]
Not sure if it makes sense for the release recipe, but shouldn't hurt either. :smirk: 

I wonder if overriding from global configuration works without using `?=`?

**Comment by jluebbe** [comment]
> Not sure if it makes sense for the release recipe, but shouldn't hurt either. 😏
> 
> I wonder if overriding from global configuration works without using `?=`?

Many recipes in meta-oe use `=` and it's consistent `SRCREV`.

**Review by Emantor — APPROVED** [review]

**Review by Emantor — APPROVED** [review]

**Comment by ejoerns** [comment]
> > Not sure if it makes sense for the release recipe, but shouldn't hurt either. 😏
> > I wonder if overriding from global configuration works without using `?=`?
> 
> Many recipes in meta-oe use `=` and it's consistent `SRCREV`.

I just checked oe-core where `?=` is used in most cases, but indeed it works with `=` when using recipe-specific overrides (which is the only sensible use case for global configuration I guess), thus fine for me.

**Comment by jluebbe** [comment]
The CI failure already exists on master and seems unrelated to this PR.

**Pull request merged**
