### PR TITLE
Update backported recipes to the version in langdale

### PR DESCRIPTION
**Pull request by hnez**
Some of the recipes no longer build on langdale as they are now older than the versions included there and e.g. lack support for newer python versions.

This PR just copies over the recipes. Another approach would be to split-off a langdale branch and just remove these recipes there as they are no longer needed there (they are however still needed e.g. in kirkstone).

### CODE REVIEW

**Review by jluebbe — APPROVED** [review]

**Comment by ejoerns** [comment]
From my perspective it makes more sense to simply drop the backports from master and stick to `kirkstone` for `kirkstone`.

**Comment by hnez** [comment]
Sounds good to me.

I will prepare and test separate PR where I remove the `kirkstone` compatibility for `master` and remove the recipes.

Do we want the updated recipes in `kirkstone` or do we want to stick with the ones that are already there in the name of stability?
If we want the updated ones I would change the target branch of this PR to `kirkstone`, if not I would just close it.

**Comment by jluebbe** [comment]
We could also drop compatibility with kirkstone now. I don't see much benefit in maintaining more than one (current) branch.

**Comment by ejoerns** [comment]
@jluebbe there is only `master` as 'current' branch, yes.

We should keep 'kirkstone' LTS buildable but it does not necessarily require recent versions. I would assume that stable updates and fixes for most components are provided by the original recipe's meta layers.

For this it would make sense to simply drop the recipes from kirkstone too, since meta-python kirkstone already contains more recent ones.

**Comment by hnez** [comment]
I've had a look at the recipes provided in `kirkstone`s `meta-python` and they are indeed also newer than the "backports" provided here.
I am going to close this PR in favor of #30, which just drops the no longer required recipes.

**Pull request closed without merging**
